# Generated by Django 4.1.7 on 2023-04-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30, unique=True)),
                ('wind_speed', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('temperature_today', models.IntegerField()),
                ('temperature_tomorrow', models.IntegerField()),
                ('temperature_after_tom', models.IntegerField()),
            ],
        ),
    ]
