# Generated by Django 4.1.7 on 2023-04-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='continent',
        ),
    ]
