# Generated by Django 4.1.7 on 2023-04-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_remove_weather_continent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent_name', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
