# Generated by Django 4.1.7 on 2023-04-16 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_continent_delete_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30, unique=True)),
                ('wind_speed', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('temperature_today', models.IntegerField()),
                ('temperature_tomorrow', models.IntegerField()),
                ('temperature_after_tom', models.IntegerField()),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather_app.continent')),
            ],
        ),
    ]
