# Generated by Django 4.1.7 on 2023-04-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0007_alter_continent_continent_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='continent_img',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dateweather',
            name='status_icon',
            field=models.TextField(blank=True),
        ),
    ]
